archives:
- id: archive
  name_template: '{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}'
before:
  hooks:
  - make tfgen
blobs:
- bucket: get.pulumi.com
  folder: releases/plugins/
  ids:
  - archive
  provider: s3
  region: us-west-2
builds:
- binary: pulumi-resource-libvirt
  dir: provider
  env:
  - CGO_ENABLED=1
  goarch:
  - amd64
  goos:
  - linux
  ldflags:
  - -X github.com/pulumi/pulumi-libvirt/provider/pkg/version.Version={{.Tag}}
  main: ./cmd/pulumi-resource-libvirt/
changelog:
  skip: true
release:
  disable: true
snapshot:
  name_template: '{{ .Tag }}-SNAPSHOT'
checksum:
  name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}_{{ .Version }}_checksums.txt"
