// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Immutable;

namespace Pulumi.Libvirt
{
    public static class Config
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "IDE1006", Justification = 
        "Double underscore prefix used to avoid conflicts with variable names.")]
        private sealed class __Value<T>
        {
            private readonly Func<T> _getter;
            private T _value = default!;
            private bool _set;

            public __Value(Func<T> getter)
            {
                _getter = getter;
            }

            public T Get() => _set ? _value : _getter();

            public void Set(T value)
            {
                _value = value;
                _set = true;
            }
        }

        private static readonly Pulumi.Config __config = new Pulumi.Config("libvirt");

        private static readonly __Value<string?> _uri = new __Value<string?>(() => __config.Get("uri") ?? Utilities.GetEnv("LIBVIRT_DEFAULT_URI"));
        /// <summary>
        /// libvirt connection URI for operations. See https://libvirt.org/uri.html
        /// </summary>
        public static string? Uri
        {
            get => _uri.Get();
            set => _uri.Set(value);
        }

    }
}
