// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.libvirt.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class DomainGraphics {
    /**
     * @return defaults to &#34;yes&#34;
     * 
     */
    private @Nullable Boolean autoport;
    /**
     * @return IP Address where the VNC listener should be started if
     * `listen_type` is set to `address`. Defaults to 127.0.0.1
     * 
     */
    private @Nullable String listenAddress;
    /**
     * @return &#34;listen type&#34;, defaults to &#34;none&#34;
     * 
     */
    private @Nullable String listenType;
    /**
     * @return The type of hypervisor to use for the domain.  Defaults to `kvm`, other values can be found [here](https://libvirt.org/formatdomain.html#id1)
     * 
     */
    private @Nullable String type;
    /**
     * @return Port to listen on for VNC WebSocket functionality (-1 meaning auto-allocation)
     * 
     * On occasion we have found it necessary to set a `type` of `vnc` and a
     * `listen_type` of `address` with certain builds of QEMU.
     * 
     * With `listen_address` it is possible to specify a listener address for the virtual
     * machines VNC server. Usually this is an IP of the host system.
     * 
     * The `graphics` block will look as follows:
     * 
     */
    private @Nullable Integer websocket;

    private DomainGraphics() {}
    /**
     * @return defaults to &#34;yes&#34;
     * 
     */
    public Optional<Boolean> autoport() {
        return Optional.ofNullable(this.autoport);
    }
    /**
     * @return IP Address where the VNC listener should be started if
     * `listen_type` is set to `address`. Defaults to 127.0.0.1
     * 
     */
    public Optional<String> listenAddress() {
        return Optional.ofNullable(this.listenAddress);
    }
    /**
     * @return &#34;listen type&#34;, defaults to &#34;none&#34;
     * 
     */
    public Optional<String> listenType() {
        return Optional.ofNullable(this.listenType);
    }
    /**
     * @return The type of hypervisor to use for the domain.  Defaults to `kvm`, other values can be found [here](https://libvirt.org/formatdomain.html#id1)
     * 
     */
    public Optional<String> type() {
        return Optional.ofNullable(this.type);
    }
    /**
     * @return Port to listen on for VNC WebSocket functionality (-1 meaning auto-allocation)
     * 
     * On occasion we have found it necessary to set a `type` of `vnc` and a
     * `listen_type` of `address` with certain builds of QEMU.
     * 
     * With `listen_address` it is possible to specify a listener address for the virtual
     * machines VNC server. Usually this is an IP of the host system.
     * 
     * The `graphics` block will look as follows:
     * 
     */
    public Optional<Integer> websocket() {
        return Optional.ofNullable(this.websocket);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(DomainGraphics defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable Boolean autoport;
        private @Nullable String listenAddress;
        private @Nullable String listenType;
        private @Nullable String type;
        private @Nullable Integer websocket;
        public Builder() {}
        public Builder(DomainGraphics defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.autoport = defaults.autoport;
    	      this.listenAddress = defaults.listenAddress;
    	      this.listenType = defaults.listenType;
    	      this.type = defaults.type;
    	      this.websocket = defaults.websocket;
        }

        @CustomType.Setter
        public Builder autoport(@Nullable Boolean autoport) {

            this.autoport = autoport;
            return this;
        }
        @CustomType.Setter
        public Builder listenAddress(@Nullable String listenAddress) {

            this.listenAddress = listenAddress;
            return this;
        }
        @CustomType.Setter
        public Builder listenType(@Nullable String listenType) {

            this.listenType = listenType;
            return this;
        }
        @CustomType.Setter
        public Builder type(@Nullable String type) {

            this.type = type;
            return this;
        }
        @CustomType.Setter
        public Builder websocket(@Nullable Integer websocket) {

            this.websocket = websocket;
            return this;
        }
        public DomainGraphics build() {
            final var _resultValue = new DomainGraphics();
            _resultValue.autoport = autoport;
            _resultValue.listenAddress = listenAddress;
            _resultValue.listenType = listenType;
            _resultValue.type = type;
            _resultValue.websocket = websocket;
            return _resultValue;
        }
    }
}
