// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.libvirt.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class DomainFilesystem {
    private @Nullable String accessmode;
    private @Nullable Boolean readonly;
    private String source;
    private String target;

    private DomainFilesystem() {}
    public Optional<String> accessmode() {
        return Optional.ofNullable(this.accessmode);
    }
    public Optional<Boolean> readonly() {
        return Optional.ofNullable(this.readonly);
    }
    public String source() {
        return this.source;
    }
    public String target() {
        return this.target;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(DomainFilesystem defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String accessmode;
        private @Nullable Boolean readonly;
        private String source;
        private String target;
        public Builder() {}
        public Builder(DomainFilesystem defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.accessmode = defaults.accessmode;
    	      this.readonly = defaults.readonly;
    	      this.source = defaults.source;
    	      this.target = defaults.target;
        }

        @CustomType.Setter
        public Builder accessmode(@Nullable String accessmode) {
            this.accessmode = accessmode;
            return this;
        }
        @CustomType.Setter
        public Builder readonly(@Nullable Boolean readonly) {
            this.readonly = readonly;
            return this;
        }
        @CustomType.Setter
        public Builder source(String source) {
            this.source = Objects.requireNonNull(source);
            return this;
        }
        @CustomType.Setter
        public Builder target(String target) {
            this.target = Objects.requireNonNull(target);
            return this;
        }
        public DomainFilesystem build() {
            final var o = new DomainFilesystem();
            o.accessmode = accessmode;
            o.readonly = readonly;
            o.source = source;
            o.target = target;
            return o;
        }
    }
}
