// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.libvirt.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class DomainDisk {
    /**
     * @return The path to the host device to use as the block device for this disk.
     * 
     */
    private final @Nullable String blockDevice;
    /**
     * @return The filename to use as the block device for this disk (read-only)
     * 
     */
    private final @Nullable String file;
    /**
     * @return Use a scsi controller for this disk.  The controller
     * model is set to `virtio-scsi`
     * 
     */
    private final @Nullable Boolean scsi;
    /**
     * @return The http url to use as the block device for this disk (read-only)
     * 
     */
    private final @Nullable String url;
    /**
     * @return The volume id to use for this disk.
     * 
     */
    private final @Nullable String volumeId;
    /**
     * @return Specify a WWN to use for the disk if the disk is using
     * a scsi controller, if not specified then a random wwn is generated for the disk
     * 
     */
    private final @Nullable String wwn;

    @CustomType.Constructor
    private DomainDisk(
        @CustomType.Parameter("blockDevice") @Nullable String blockDevice,
        @CustomType.Parameter("file") @Nullable String file,
        @CustomType.Parameter("scsi") @Nullable Boolean scsi,
        @CustomType.Parameter("url") @Nullable String url,
        @CustomType.Parameter("volumeId") @Nullable String volumeId,
        @CustomType.Parameter("wwn") @Nullable String wwn) {
        this.blockDevice = blockDevice;
        this.file = file;
        this.scsi = scsi;
        this.url = url;
        this.volumeId = volumeId;
        this.wwn = wwn;
    }

    /**
     * @return The path to the host device to use as the block device for this disk.
     * 
     */
    public Optional<String> blockDevice() {
        return Optional.ofNullable(this.blockDevice);
    }
    /**
     * @return The filename to use as the block device for this disk (read-only)
     * 
     */
    public Optional<String> file() {
        return Optional.ofNullable(this.file);
    }
    /**
     * @return Use a scsi controller for this disk.  The controller
     * model is set to `virtio-scsi`
     * 
     */
    public Optional<Boolean> scsi() {
        return Optional.ofNullable(this.scsi);
    }
    /**
     * @return The http url to use as the block device for this disk (read-only)
     * 
     */
    public Optional<String> url() {
        return Optional.ofNullable(this.url);
    }
    /**
     * @return The volume id to use for this disk.
     * 
     */
    public Optional<String> volumeId() {
        return Optional.ofNullable(this.volumeId);
    }
    /**
     * @return Specify a WWN to use for the disk if the disk is using
     * a scsi controller, if not specified then a random wwn is generated for the disk
     * 
     */
    public Optional<String> wwn() {
        return Optional.ofNullable(this.wwn);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(DomainDisk defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private @Nullable String blockDevice;
        private @Nullable String file;
        private @Nullable Boolean scsi;
        private @Nullable String url;
        private @Nullable String volumeId;
        private @Nullable String wwn;

        public Builder() {
    	      // Empty
        }

        public Builder(DomainDisk defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.blockDevice = defaults.blockDevice;
    	      this.file = defaults.file;
    	      this.scsi = defaults.scsi;
    	      this.url = defaults.url;
    	      this.volumeId = defaults.volumeId;
    	      this.wwn = defaults.wwn;
        }

        public Builder blockDevice(@Nullable String blockDevice) {
            this.blockDevice = blockDevice;
            return this;
        }
        public Builder file(@Nullable String file) {
            this.file = file;
            return this;
        }
        public Builder scsi(@Nullable Boolean scsi) {
            this.scsi = scsi;
            return this;
        }
        public Builder url(@Nullable String url) {
            this.url = url;
            return this;
        }
        public Builder volumeId(@Nullable String volumeId) {
            this.volumeId = volumeId;
            return this;
        }
        public Builder wwn(@Nullable String wwn) {
            this.wwn = wwn;
            return this;
        }        public DomainDisk build() {
            return new DomainDisk(blockDevice, file, scsi, url, volumeId, wwn);
        }
    }
}
