// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.libvirt.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class DomainNvram {
    /**
     * @return The filename to use as the block device for this disk (read-only)
     * 
     */
    private final String file;
    /**
     * @return path to the file used to override variables from the master NVRAM
     * store.
     * 
     */
    private final @Nullable String template;

    @CustomType.Constructor
    private DomainNvram(
        @CustomType.Parameter("file") String file,
        @CustomType.Parameter("template") @Nullable String template) {
        this.file = file;
        this.template = template;
    }

    /**
     * @return The filename to use as the block device for this disk (read-only)
     * 
     */
    public String file() {
        return this.file;
    }
    /**
     * @return path to the file used to override variables from the master NVRAM
     * store.
     * 
     */
    public Optional<String> template() {
        return Optional.ofNullable(this.template);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(DomainNvram defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private String file;
        private @Nullable String template;

        public Builder() {
    	      // Empty
        }

        public Builder(DomainNvram defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.file = defaults.file;
    	      this.template = defaults.template;
        }

        public Builder file(String file) {
            this.file = Objects.requireNonNull(file);
            return this;
        }
        public Builder template(@Nullable String template) {
            this.template = template;
            return this;
        }        public DomainNvram build() {
            return new DomainNvram(file, template);
        }
    }
}
