// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.libvirt.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class DomainFilesystem {
    /**
     * @return specifies the security mode for accessing the source. By default
     * the `mapped` mode is chosen.
     * 
     */
    private @Nullable String accessmode;
    /**
     * @return enables exporting filesystem as a readonly mount for guest, by
     * default read-only access is given.
     * 
     * Example:
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     * The exported filesystems can be mounted inside of the guest in this way:
     * 
     */
    private @Nullable Boolean readonly;
    /**
     * @return the directory of the host to be shared with the guest.
     * 
     */
    private String source;
    /**
     * @return an arbitrary string tag that is exported to the guest as a hint for
     * where to mount the source.
     * 
     */
    private String target;

    private DomainFilesystem() {}
    /**
     * @return specifies the security mode for accessing the source. By default
     * the `mapped` mode is chosen.
     * 
     */
    public Optional<String> accessmode() {
        return Optional.ofNullable(this.accessmode);
    }
    /**
     * @return enables exporting filesystem as a readonly mount for guest, by
     * default read-only access is given.
     * 
     * Example:
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     * The exported filesystems can be mounted inside of the guest in this way:
     * 
     */
    public Optional<Boolean> readonly() {
        return Optional.ofNullable(this.readonly);
    }
    /**
     * @return the directory of the host to be shared with the guest.
     * 
     */
    public String source() {
        return this.source;
    }
    /**
     * @return an arbitrary string tag that is exported to the guest as a hint for
     * where to mount the source.
     * 
     */
    public String target() {
        return this.target;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(DomainFilesystem defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String accessmode;
        private @Nullable Boolean readonly;
        private String source;
        private String target;
        public Builder() {}
        public Builder(DomainFilesystem defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.accessmode = defaults.accessmode;
    	      this.readonly = defaults.readonly;
    	      this.source = defaults.source;
    	      this.target = defaults.target;
        }

        @CustomType.Setter
        public Builder accessmode(@Nullable String accessmode) {

            this.accessmode = accessmode;
            return this;
        }
        @CustomType.Setter
        public Builder readonly(@Nullable Boolean readonly) {

            this.readonly = readonly;
            return this;
        }
        @CustomType.Setter
        public Builder source(String source) {
            if (source == null) {
              throw new MissingRequiredPropertyException("DomainFilesystem", "source");
            }
            this.source = source;
            return this;
        }
        @CustomType.Setter
        public Builder target(String target) {
            if (target == null) {
              throw new MissingRequiredPropertyException("DomainFilesystem", "target");
            }
            this.target = target;
            return this;
        }
        public DomainFilesystem build() {
            final var _resultValue = new DomainFilesystem();
            _resultValue.accessmode = accessmode;
            _resultValue.readonly = readonly;
            _resultValue.source = source;
            _resultValue.target = target;
            return _resultValue;
        }
    }
}
