// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.libvirt.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetNetworkDnsSrvTemplateResult {
    private @Nullable String domain;
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private String id;
    private @Nullable String port;
    private @Nullable String priority;
    private String protocol;
    private Map<String,String> rendered;
    private String service;
    private @Nullable String target;
    private @Nullable String weight;

    private GetNetworkDnsSrvTemplateResult() {}
    public Optional<String> domain() {
        return Optional.ofNullable(this.domain);
    }
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }
    public Optional<String> port() {
        return Optional.ofNullable(this.port);
    }
    public Optional<String> priority() {
        return Optional.ofNullable(this.priority);
    }
    public String protocol() {
        return this.protocol;
    }
    public Map<String,String> rendered() {
        return this.rendered;
    }
    public String service() {
        return this.service;
    }
    public Optional<String> target() {
        return Optional.ofNullable(this.target);
    }
    public Optional<String> weight() {
        return Optional.ofNullable(this.weight);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetNetworkDnsSrvTemplateResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String domain;
        private String id;
        private @Nullable String port;
        private @Nullable String priority;
        private String protocol;
        private Map<String,String> rendered;
        private String service;
        private @Nullable String target;
        private @Nullable String weight;
        public Builder() {}
        public Builder(GetNetworkDnsSrvTemplateResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.domain = defaults.domain;
    	      this.id = defaults.id;
    	      this.port = defaults.port;
    	      this.priority = defaults.priority;
    	      this.protocol = defaults.protocol;
    	      this.rendered = defaults.rendered;
    	      this.service = defaults.service;
    	      this.target = defaults.target;
    	      this.weight = defaults.weight;
        }

        @CustomType.Setter
        public Builder domain(@Nullable String domain) {

            this.domain = domain;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetNetworkDnsSrvTemplateResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder port(@Nullable String port) {

            this.port = port;
            return this;
        }
        @CustomType.Setter
        public Builder priority(@Nullable String priority) {

            this.priority = priority;
            return this;
        }
        @CustomType.Setter
        public Builder protocol(String protocol) {
            if (protocol == null) {
              throw new MissingRequiredPropertyException("GetNetworkDnsSrvTemplateResult", "protocol");
            }
            this.protocol = protocol;
            return this;
        }
        @CustomType.Setter
        public Builder rendered(Map<String,String> rendered) {
            if (rendered == null) {
              throw new MissingRequiredPropertyException("GetNetworkDnsSrvTemplateResult", "rendered");
            }
            this.rendered = rendered;
            return this;
        }
        @CustomType.Setter
        public Builder service(String service) {
            if (service == null) {
              throw new MissingRequiredPropertyException("GetNetworkDnsSrvTemplateResult", "service");
            }
            this.service = service;
            return this;
        }
        @CustomType.Setter
        public Builder target(@Nullable String target) {

            this.target = target;
            return this;
        }
        @CustomType.Setter
        public Builder weight(@Nullable String weight) {

            this.weight = weight;
            return this;
        }
        public GetNetworkDnsSrvTemplateResult build() {
            final var _resultValue = new GetNetworkDnsSrvTemplateResult();
            _resultValue.domain = domain;
            _resultValue.id = id;
            _resultValue.port = port;
            _resultValue.priority = priority;
            _resultValue.protocol = protocol;
            _resultValue.rendered = rendered;
            _resultValue.service = service;
            _resultValue.target = target;
            _resultValue.weight = weight;
            return _resultValue;
        }
    }
}
