// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.libvirt.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class NetworkDnsSrv {
    /**
     * @return The domain used by the DNS server.
     * 
     */
    private final @Nullable String domain;
    private final @Nullable String port;
    private final @Nullable String priority;
    private final @Nullable String protocol;
    private final @Nullable String service;
    private final @Nullable String target;
    private final @Nullable String weight;

    @CustomType.Constructor
    private NetworkDnsSrv(
        @CustomType.Parameter("domain") @Nullable String domain,
        @CustomType.Parameter("port") @Nullable String port,
        @CustomType.Parameter("priority") @Nullable String priority,
        @CustomType.Parameter("protocol") @Nullable String protocol,
        @CustomType.Parameter("service") @Nullable String service,
        @CustomType.Parameter("target") @Nullable String target,
        @CustomType.Parameter("weight") @Nullable String weight) {
        this.domain = domain;
        this.port = port;
        this.priority = priority;
        this.protocol = protocol;
        this.service = service;
        this.target = target;
        this.weight = weight;
    }

    /**
     * @return The domain used by the DNS server.
     * 
     */
    public Optional<String> domain() {
        return Optional.ofNullable(this.domain);
    }
    public Optional<String> port() {
        return Optional.ofNullable(this.port);
    }
    public Optional<String> priority() {
        return Optional.ofNullable(this.priority);
    }
    public Optional<String> protocol() {
        return Optional.ofNullable(this.protocol);
    }
    public Optional<String> service() {
        return Optional.ofNullable(this.service);
    }
    public Optional<String> target() {
        return Optional.ofNullable(this.target);
    }
    public Optional<String> weight() {
        return Optional.ofNullable(this.weight);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(NetworkDnsSrv defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private @Nullable String domain;
        private @Nullable String port;
        private @Nullable String priority;
        private @Nullable String protocol;
        private @Nullable String service;
        private @Nullable String target;
        private @Nullable String weight;

        public Builder() {
    	      // Empty
        }

        public Builder(NetworkDnsSrv defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.domain = defaults.domain;
    	      this.port = defaults.port;
    	      this.priority = defaults.priority;
    	      this.protocol = defaults.protocol;
    	      this.service = defaults.service;
    	      this.target = defaults.target;
    	      this.weight = defaults.weight;
        }

        public Builder domain(@Nullable String domain) {
            this.domain = domain;
            return this;
        }
        public Builder port(@Nullable String port) {
            this.port = port;
            return this;
        }
        public Builder priority(@Nullable String priority) {
            this.priority = priority;
            return this;
        }
        public Builder protocol(@Nullable String protocol) {
            this.protocol = protocol;
            return this;
        }
        public Builder service(@Nullable String service) {
            this.service = service;
            return this;
        }
        public Builder target(@Nullable String target) {
            this.target = target;
            return this;
        }
        public Builder weight(@Nullable String weight) {
            this.weight = weight;
            return this;
        }        public NetworkDnsSrv build() {
            return new NetworkDnsSrv(domain, port, priority, protocol, service, target, weight);
        }
    }
}
