// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.libvirt.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class NetworkDnsmasqOptionsOption {
    private final @Nullable String optionName;
    private final @Nullable String optionValue;

    @CustomType.Constructor
    private NetworkDnsmasqOptionsOption(
        @CustomType.Parameter("optionName") @Nullable String optionName,
        @CustomType.Parameter("optionValue") @Nullable String optionValue) {
        this.optionName = optionName;
        this.optionValue = optionValue;
    }

    public Optional<String> optionName() {
        return Optional.ofNullable(this.optionName);
    }
    public Optional<String> optionValue() {
        return Optional.ofNullable(this.optionValue);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(NetworkDnsmasqOptionsOption defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private @Nullable String optionName;
        private @Nullable String optionValue;

        public Builder() {
    	      // Empty
        }

        public Builder(NetworkDnsmasqOptionsOption defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.optionName = defaults.optionName;
    	      this.optionValue = defaults.optionValue;
        }

        public Builder optionName(@Nullable String optionName) {
            this.optionName = optionName;
            return this;
        }
        public Builder optionValue(@Nullable String optionValue) {
            this.optionValue = optionValue;
            return this;
        }        public NetworkDnsmasqOptionsOption build() {
            return new NetworkDnsmasqOptionsOption(optionName, optionValue);
        }
    }
}
