// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.libvirt;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.libvirt.DomainArgs;
import com.pulumi.libvirt.Utilities;
import com.pulumi.libvirt.inputs.DomainState;
import com.pulumi.libvirt.outputs.DomainBootDevice;
import com.pulumi.libvirt.outputs.DomainConsole;
import com.pulumi.libvirt.outputs.DomainCpu;
import com.pulumi.libvirt.outputs.DomainDisk;
import com.pulumi.libvirt.outputs.DomainFilesystem;
import com.pulumi.libvirt.outputs.DomainGraphics;
import com.pulumi.libvirt.outputs.DomainNetworkInterface;
import com.pulumi.libvirt.outputs.DomainNvram;
import com.pulumi.libvirt.outputs.DomainTpm;
import com.pulumi.libvirt.outputs.DomainVideo;
import com.pulumi.libvirt.outputs.DomainXml;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Manages a VM domain resource within libvirt. For more information see
 * [the official documentation](https://libvirt.org/formatdomain.html).
 * 
 * ## Example Usage
 * 
 * &lt;!--Start PulumiCodeChooser --&gt;
 * ```java
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.libvirt.Domain;
 * import com.pulumi.libvirt.DomainArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var default_ = new Domain(&#34;default&#34;, DomainArgs.builder()        
 *             .name(&#34;test&#34;)
 *             .build());
 * 
 *     }
 * }
 * ```
 * &lt;!--End PulumiCodeChooser --&gt;
 * 
 */
@ResourceType(type="libvirt:index/domain:Domain")
public class Domain extends com.pulumi.resources.CustomResource {
    /**
     * The architecture for the VM (probably x86_64 or i686),
     * you normally won&#39;t need to set this unless you are building a special VM
     * 
     */
    @Export(name="arch", refs={String.class}, tree="[0]")
    private Output<String> arch;

    /**
     * @return The architecture for the VM (probably x86_64 or i686),
     * you normally won&#39;t need to set this unless you are building a special VM
     * 
     */
    public Output<String> arch() {
        return this.arch;
    }
    /**
     * Set to `true` to start the domain on host boot up.
     * If not specified `false` is assumed.
     * 
     */
    @Export(name="autostart", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> autostart;

    /**
     * @return Set to `true` to start the domain on host boot up.
     * If not specified `false` is assumed.
     * 
     */
    public Output<Boolean> autostart() {
        return this.autostart;
    }
    /**
     * A list of devices (dev) which defines boot order. Example
     * below.
     * 
     */
    @Export(name="bootDevices", refs={List.class,DomainBootDevice.class}, tree="[0,1]")
    private Output</* @Nullable */ List<DomainBootDevice>> bootDevices;

    /**
     * @return A list of devices (dev) which defines boot order. Example
     * below.
     * 
     */
    public Output<Optional<List<DomainBootDevice>>> bootDevices() {
        return Codegen.optional(this.bootDevices);
    }
    /**
     * The `libvirt.CloudInitDisk` disk that has to be used by
     * the domain. This is going to be attached as a CDROM ISO. Changing the
     * cloud-init won&#39;t cause the domain to be recreated, however the change will
     * have effect on the next reboot.
     * 
     */
    @Export(name="cloudinit", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> cloudinit;

    /**
     * @return The `libvirt.CloudInitDisk` disk that has to be used by
     * the domain. This is going to be attached as a CDROM ISO. Changing the
     * cloud-init won&#39;t cause the domain to be recreated, however the change will
     * have effect on the next reboot.
     * 
     */
    public Output<Optional<String>> cloudinit() {
        return Codegen.optional(this.cloudinit);
    }
    @Export(name="cmdlines", refs={List.class,Map.class,String.class,Object.class}, tree="[0,[1,2,3]]")
    private Output</* @Nullable */ List<Map<String,Object>>> cmdlines;

    public Output<Optional<List<Map<String,Object>>>> cmdlines() {
        return Codegen.optional(this.cmdlines);
    }
    @Export(name="consoles", refs={List.class,DomainConsole.class}, tree="[0,1]")
    private Output</* @Nullable */ List<DomainConsole>> consoles;

    public Output<Optional<List<DomainConsole>>> consoles() {
        return Codegen.optional(this.consoles);
    }
    /**
     * The
     * [libvirt.Ignition](https://www.terraform.io/docs/providers/libvirt/r/coreos_ignition.html) resource
     * that is to be used by the CoreOS domain.
     * 
     */
    @Export(name="coreosIgnition", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> coreosIgnition;

    /**
     * @return The
     * [libvirt.Ignition](https://www.terraform.io/docs/providers/libvirt/r/coreos_ignition.html) resource
     * that is to be used by the CoreOS domain.
     * 
     */
    public Output<Optional<String>> coreosIgnition() {
        return Codegen.optional(this.coreosIgnition);
    }
    /**
     * Configures CPU mode. See below for more
     * details.
     * 
     */
    @Export(name="cpu", refs={DomainCpu.class}, tree="[0]")
    private Output<DomainCpu> cpu;

    /**
     * @return Configures CPU mode. See below for more
     * details.
     * 
     */
    public Output<DomainCpu> cpu() {
        return this.cpu;
    }
    /**
     * The description for domain.
     * Changing this forces a new resource to be created.
     * This data is not used by libvirt in any way, it can contain any information the user wants.
     * 
     */
    @Export(name="description", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> description;

    /**
     * @return The description for domain.
     * Changing this forces a new resource to be created.
     * This data is not used by libvirt in any way, it can contain any information the user wants.
     * 
     */
    public Output<Optional<String>> description() {
        return Codegen.optional(this.description);
    }
    /**
     * An array of one or more disks to attach to the domain. The
     * `disk` object structure is documented below.
     * 
     */
    @Export(name="disks", refs={List.class,DomainDisk.class}, tree="[0,1]")
    private Output</* @Nullable */ List<DomainDisk>> disks;

    /**
     * @return An array of one or more disks to attach to the domain. The
     * `disk` object structure is documented below.
     * 
     */
    public Output<Optional<List<DomainDisk>>> disks() {
        return Codegen.optional(this.disks);
    }
    /**
     * The path of the emulator to use
     * 
     */
    @Export(name="emulator", refs={String.class}, tree="[0]")
    private Output<String> emulator;

    /**
     * @return The path of the emulator to use
     * 
     */
    public Output<String> emulator() {
        return this.emulator;
    }
    /**
     * An array of one or more host filesystems to attach to
     * the domain. The `filesystem` object structure is documented
     * below.
     * 
     */
    @Export(name="filesystems", refs={List.class,DomainFilesystem.class}, tree="[0,1]")
    private Output</* @Nullable */ List<DomainFilesystem>> filesystems;

    /**
     * @return An array of one or more host filesystems to attach to
     * the domain. The `filesystem` object structure is documented
     * below.
     * 
     */
    public Output<Optional<List<DomainFilesystem>>> filesystems() {
        return Codegen.optional(this.filesystems);
    }
    @Export(name="firmware", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> firmware;

    public Output<Optional<String>> firmware() {
        return Codegen.optional(this.firmware);
    }
    /**
     * The name of the firmware config path where ignition file is stored: default is `opt/com.coreos/config`. If you are using [Flatcar Linux](https://docs.flatcar-linux.org/os/booting-with-libvirt/#creating-the-domain-xml), the value is `opt/org.flatcar-linux/config`.
     * 
     */
    @Export(name="fwCfgName", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> fwCfgName;

    /**
     * @return The name of the firmware config path where ignition file is stored: default is `opt/com.coreos/config`. If you are using [Flatcar Linux](https://docs.flatcar-linux.org/os/booting-with-libvirt/#creating-the-domain-xml), the value is `opt/org.flatcar-linux/config`.
     * 
     */
    public Output<Optional<String>> fwCfgName() {
        return Codegen.optional(this.fwCfgName);
    }
    @Export(name="graphics", refs={DomainGraphics.class}, tree="[0]")
    private Output</* @Nullable */ DomainGraphics> graphics;

    public Output<Optional<DomainGraphics>> graphics() {
        return Codegen.optional(this.graphics);
    }
    @Export(name="initrd", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> initrd;

    public Output<Optional<String>> initrd() {
        return Codegen.optional(this.initrd);
    }
    @Export(name="kernel", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> kernel;

    public Output<Optional<String>> kernel() {
        return Codegen.optional(this.kernel);
    }
    /**
     * The machine type,
     * you normally won&#39;t need to set this unless you are running on a platform that
     * defaults to the wrong machine type for your template
     * 
     */
    @Export(name="machine", refs={String.class}, tree="[0]")
    private Output<String> machine;

    /**
     * @return The machine type,
     * you normally won&#39;t need to set this unless you are running on a platform that
     * defaults to the wrong machine type for your template
     * 
     */
    public Output<String> machine() {
        return this.machine;
    }
    /**
     * The amount of memory in MiB. If not specified the domain
     * will be created with 512 MiB of memory be used.
     * 
     */
    @Export(name="memory", refs={Integer.class}, tree="[0]")
    private Output</* @Nullable */ Integer> memory;

    /**
     * @return The amount of memory in MiB. If not specified the domain
     * will be created with 512 MiB of memory be used.
     * 
     */
    public Output<Optional<Integer>> memory() {
        return Codegen.optional(this.memory);
    }
    @Export(name="metadata", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> metadata;

    public Output<Optional<String>> metadata() {
        return Codegen.optional(this.metadata);
    }
    /**
     * A unique name for the resource, required by libvirt.
     * Changing this forces a new resource to be created.
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return A unique name for the resource, required by libvirt.
     * Changing this forces a new resource to be created.
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * An array of one or more network interfaces to
     * attach to the domain. The `network_interface` object structure is documented
     * below.
     * 
     */
    @Export(name="networkInterfaces", refs={List.class,DomainNetworkInterface.class}, tree="[0,1]")
    private Output</* @Nullable */ List<DomainNetworkInterface>> networkInterfaces;

    /**
     * @return An array of one or more network interfaces to
     * attach to the domain. The `network_interface` object structure is documented
     * below.
     * 
     */
    public Output<Optional<List<DomainNetworkInterface>>> networkInterfaces() {
        return Codegen.optional(this.networkInterfaces);
    }
    @Export(name="nvram", refs={DomainNvram.class}, tree="[0]")
    private Output</* @Nullable */ DomainNvram> nvram;

    public Output<Optional<DomainNvram>> nvram() {
        return Codegen.optional(this.nvram);
    }
    /**
     * By default is disabled, set to true for enabling it. More info [qemu-agent](https://wiki.libvirt.org/page/Qemu_guest_agent).
     * 
     */
    @Export(name="qemuAgent", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> qemuAgent;

    /**
     * @return By default is disabled, set to true for enabling it. More info [qemu-agent](https://wiki.libvirt.org/page/Qemu_guest_agent).
     * 
     */
    public Output<Optional<Boolean>> qemuAgent() {
        return Codegen.optional(this.qemuAgent);
    }
    /**
     * Use `false` to turn off the instance. If not specified,
     * true is assumed and the instance, if stopped, will be started at next apply.
     * 
     */
    @Export(name="running", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> running;

    /**
     * @return Use `false` to turn off the instance. If not specified,
     * true is assumed and the instance, if stopped, will be started at next apply.
     * 
     */
    public Output<Optional<Boolean>> running() {
        return Codegen.optional(this.running);
    }
    /**
     * TPM device to attach to the domain. The `tpm` object structure is documented below.
     * 
     */
    @Export(name="tpm", refs={DomainTpm.class}, tree="[0]")
    private Output</* @Nullable */ DomainTpm> tpm;

    /**
     * @return TPM device to attach to the domain. The `tpm` object structure is documented below.
     * 
     */
    public Output<Optional<DomainTpm>> tpm() {
        return Codegen.optional(this.tpm);
    }
    /**
     * The type of hypervisor to use for the domain.  Defaults to `kvm`, other values can be found [here](https://libvirt.org/formatdomain.html#id1)
     * 
     */
    @Export(name="type", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> type;

    /**
     * @return The type of hypervisor to use for the domain.  Defaults to `kvm`, other values can be found [here](https://libvirt.org/formatdomain.html#id1)
     * 
     */
    public Output<Optional<String>> type() {
        return Codegen.optional(this.type);
    }
    /**
     * The amount of virtual CPUs. If not specified, a single CPU
     * will be created.
     * 
     */
    @Export(name="vcpu", refs={Integer.class}, tree="[0]")
    private Output</* @Nullable */ Integer> vcpu;

    /**
     * @return The amount of virtual CPUs. If not specified, a single CPU
     * will be created.
     * 
     */
    public Output<Optional<Integer>> vcpu() {
        return Codegen.optional(this.vcpu);
    }
    @Export(name="video", refs={DomainVideo.class}, tree="[0]")
    private Output</* @Nullable */ DomainVideo> video;

    public Output<Optional<DomainVideo>> video() {
        return Codegen.optional(this.video);
    }
    @Export(name="xml", refs={DomainXml.class}, tree="[0]")
    private Output</* @Nullable */ DomainXml> xml;

    public Output<Optional<DomainXml>> xml() {
        return Codegen.optional(this.xml);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Domain(String name) {
        this(name, DomainArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Domain(String name, @Nullable DomainArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Domain(String name, @Nullable DomainArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("libvirt:index/domain:Domain", name, args == null ? DomainArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private Domain(String name, Output<String> id, @Nullable DomainState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("libvirt:index/domain:Domain", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Domain get(String name, Output<String> id, @Nullable DomainState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Domain(name, id, state, options);
    }
}
