// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

let __config = new pulumi.Config("libvirt");

/**
 * libvirt connection URI for operations. See https://libvirt.org/uri.html
 */
export let uri: string | undefined = __config.get("uri") || utilities.getEnv("LIBVIRT_DEFAULT_URI");
