// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Libvirt.Outputs
{

    [OutputType]
    public sealed class DomainFilesystem
    {
        public readonly string? Accessmode;
        public readonly bool? Readonly;
        public readonly string Source;
        public readonly string Target;

        [OutputConstructor]
        private DomainFilesystem(
            string? accessmode,

            bool? @readonly,

            string source,

            string target)
        {
            Accessmode = accessmode;
            Readonly = @readonly;
            Source = source;
            Target = target;
        }
    }
}
