// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Libvirt.Outputs
{

    [OutputType]
    public sealed class DomainNvram
    {
        /// <summary>
        /// path to the file backing the NVRAM store for non-volatile variables. When provided,
        /// this file must be writable and specific to this domain, as it will be updated when running the
        /// domain. However, `libvirt` can  manage this automatically (and this is the recommended solution)
        /// if a mapping for the firmware to a _variables file_ exists in `/etc/libvirt/qemu.conf:nvram`.
        /// In that case, `libvirt` will copy that variables file into a file specific for this domain.
        /// </summary>
        public readonly string File;
        /// <summary>
        /// path to the file used to override variables from the master NVRAM
        /// store.
        /// 
        /// So you should typically use the firmware as this,
        /// 
        /// 
        /// and `/etc/libvirt/qemu.conf` should contain:
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        /// });
        /// ```
        /// 
        /// In case you need (or want) to specify the path for the NVRAM store, the domain definition should
        /// look like this:
        /// 
        /// 
        /// Finally, if you want the initial values for the NVRAM to be overridden by custom initial values
        /// coming from a template, the domain definition should look like this:
        /// </summary>
        public readonly string? Template;

        [OutputConstructor]
        private DomainNvram(
            string file,

            string? template)
        {
            File = file;
            Template = template;
        }
    }
}
