// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Libvirt.Outputs
{

    [OutputType]
    public sealed class GetNodeDeviceInfoDevnodeResult
    {
        /// <summary>
        /// Full path of the device
        /// </summary>
        public readonly string Path;
        /// <summary>
        /// Device type: `pci`, `storage`, `usb`
        /// </summary>
        public readonly string Type;

        [OutputConstructor]
        private GetNodeDeviceInfoDevnodeResult(
            string path,

            string type)
        {
            Path = path;
            Type = type;
        }
    }
}
