// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package libvirt

import (
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

func GetNetworkDnsHostTemplate(ctx *pulumi.Context, args *GetNetworkDnsHostTemplateArgs, opts ...pulumi.InvokeOption) (*GetNetworkDnsHostTemplateResult, error) {
	var rv GetNetworkDnsHostTemplateResult
	err := ctx.Invoke("libvirt:index/getNetworkDnsHostTemplate:getNetworkDnsHostTemplate", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getNetworkDnsHostTemplate.
type GetNetworkDnsHostTemplateArgs struct {
	Hostname string `pulumi:"hostname"`
	Ip       string `pulumi:"ip"`
}

// A collection of values returned by getNetworkDnsHostTemplate.
type GetNetworkDnsHostTemplateResult struct {
	Hostname string `pulumi:"hostname"`
	// The provider-assigned unique ID for this managed resource.
	Id       string            `pulumi:"id"`
	Ip       string            `pulumi:"ip"`
	Rendered map[string]string `pulumi:"rendered"`
}
