// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package libvirt

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "libvirt:index/cloudInitDisk:CloudInitDisk":
		r, err = NewCloudInitDisk(ctx, name, nil, pulumi.URN_(urn))
	case "libvirt:index/domain:Domain":
		r, err = NewDomain(ctx, name, nil, pulumi.URN_(urn))
	case "libvirt:index/ignition:Ignition":
		r, err = NewIgnition(ctx, name, nil, pulumi.URN_(urn))
	case "libvirt:index/network:Network":
		r, err = NewNetwork(ctx, name, nil, pulumi.URN_(urn))
	case "libvirt:index/pool:Pool":
		r, err = NewPool(ctx, name, nil, pulumi.URN_(urn))
	case "libvirt:index/volume:Volume":
		r, err = NewVolume(ctx, name, nil, pulumi.URN_(urn))
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	return
}

type pkg struct {
	version semver.Version
}

func (p *pkg) Version() semver.Version {
	return p.version
}

func (p *pkg) ConstructProvider(ctx *pulumi.Context, name, typ, urn string) (pulumi.ProviderResource, error) {
	if typ != "pulumi:providers:libvirt" {
		return nil, fmt.Errorf("unknown provider type: %s", typ)
	}

	return NewProvider(ctx, name, nil, pulumi.URN_(urn))
}

func init() {
	version, err := PkgVersion()
	if err != nil {
		fmt.Println("failed to determine package version. defaulting to v1: %v", err)
	}
	pulumi.RegisterResourceModule(
		"libvirt",
		"index/cloudInitDisk",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"libvirt",
		"index/domain",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"libvirt",
		"index/ignition",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"libvirt",
		"index/network",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"libvirt",
		"index/pool",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"libvirt",
		"index/volume",
		&module{version},
	)
	pulumi.RegisterResourcePackage(
		"libvirt",
		&pkg{version},
	)
}
