# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

SNAKE_TO_CAMEL_CASE_TABLE = {
    "base_volume_id": "baseVolumeId",
    "base_volume_name": "baseVolumeName",
    "base_volume_pool": "baseVolumePool",
    "boot_devices": "bootDevices",
    "coreos_ignition": "coreosIgnition",
    "fw_cfg_name": "fwCfgName",
    "meta_data": "metaData",
    "network_config": "networkConfig",
    "network_interfaces": "networkInterfaces",
    "qemu_agent": "qemuAgent",
    "user_data": "userData",
}

CAMEL_TO_SNAKE_CASE_TABLE = {
    "baseVolumeId": "base_volume_id",
    "baseVolumeName": "base_volume_name",
    "baseVolumePool": "base_volume_pool",
    "bootDevices": "boot_devices",
    "coreosIgnition": "coreos_ignition",
    "fwCfgName": "fw_cfg_name",
    "metaData": "meta_data",
    "networkConfig": "network_config",
    "networkInterfaces": "network_interfaces",
    "qemuAgent": "qemu_agent",
    "userData": "user_data",
}
