// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.libvirt.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;


public final class DomainCpuArgs extends com.pulumi.resources.ResourceArgs {

    public static final DomainCpuArgs Empty = new DomainCpuArgs();

    @Import(name="mode", required=true)
    private Output<String> mode;

    public Output<String> mode() {
        return this.mode;
    }

    private DomainCpuArgs() {}

    private DomainCpuArgs(DomainCpuArgs $) {
        this.mode = $.mode;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(DomainCpuArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private DomainCpuArgs $;

        public Builder() {
            $ = new DomainCpuArgs();
        }

        public Builder(DomainCpuArgs defaults) {
            $ = new DomainCpuArgs(Objects.requireNonNull(defaults));
        }

        public Builder mode(Output<String> mode) {
            $.mode = mode;
            return this;
        }

        public Builder mode(String mode) {
            return mode(Output.of(mode));
        }

        public DomainCpuArgs build() {
            $.mode = Objects.requireNonNull($.mode, "expected parameter 'mode' to be non-null");
            return $;
        }
    }

}
