// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Libvirt.Inputs
{

    public sealed class DomainDiskArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// The path to the host device to use as the block device for this disk.
        /// </summary>
        [Input("blockDevice")]
        public Input<string>? BlockDevice { get; set; }

        /// <summary>
        /// The filename to use as the block device for this disk (read-only)
        /// </summary>
        [Input("file")]
        public Input<string>? File { get; set; }

        /// <summary>
        /// Use a scsi controller for this disk.  The controller
        /// model is set to `virtio-scsi`
        /// </summary>
        [Input("scsi")]
        public Input<bool>? Scsi { get; set; }

        /// <summary>
        /// The http url to use as the block device for this disk (read-only)
        /// </summary>
        [Input("url")]
        public Input<string>? Url { get; set; }

        /// <summary>
        /// The volume id to use for this disk.
        /// </summary>
        [Input("volumeId")]
        public Input<string>? VolumeId { get; set; }

        /// <summary>
        /// Specify a WWN to use for the disk if the disk is using
        /// a scsi controller, if not specified then a random wwn is generated for the disk
        /// </summary>
        [Input("wwn")]
        public Input<string>? Wwn { get; set; }

        public DomainDiskArgs()
        {
        }
    }
}
