// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Libvirt.Inputs
{

    public sealed class DomainNvramArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The filename to use as the block device for this disk (read-only)
        /// </summary>
        [Input("file", required: true)]
        public Input<string> File { get; set; } = null!;

        /// <summary>
        /// path to the file used to override variables from the master NVRAM
        /// store.
        /// </summary>
        [Input("template")]
        public Input<string>? Template { get; set; }

        public DomainNvramArgs()
        {
        }
        public static new DomainNvramArgs Empty => new DomainNvramArgs();
    }
}
