// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Libvirt.Inputs
{

    public sealed class GetNodeDeviceInfoCapabilityIommuGroupArgs : global::Pulumi.InvokeArgs
    {
        [Input("addresses", required: true)]
        private List<ImmutableDictionary<string, string>>? _addresses;
        public List<ImmutableDictionary<string, string>> Addresses
        {
            get => _addresses ?? (_addresses = new List<ImmutableDictionary<string, string>>());
            set => _addresses = value;
        }

        /// <summary>
        /// Device number
        /// </summary>
        [Input("number", required: true)]
        public string Number { get; set; } = null!;

        public GetNodeDeviceInfoCapabilityIommuGroupArgs()
        {
        }
        public static new GetNodeDeviceInfoCapabilityIommuGroupArgs Empty => new GetNodeDeviceInfoCapabilityIommuGroupArgs();
    }
}
