// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Libvirt.Inputs
{

    public sealed class NetworkDnsmasqOptionsArgs : global::Pulumi.ResourceArgs
    {
        [Input("options")]
        private InputList<Inputs.NetworkDnsmasqOptionsOptionArgs>? _options;

        /// <summary>
        /// a Dnsmasq option entry block. You can have one or more of these
        /// blocks in your definition. You must specify both `option_name` and `option_value`.
        /// </summary>
        public InputList<Inputs.NetworkDnsmasqOptionsOptionArgs> Options
        {
            get => _options ?? (_options = new InputList<Inputs.NetworkDnsmasqOptionsOptionArgs>());
            set => _options = value;
        }

        public NetworkDnsmasqOptionsArgs()
        {
        }
        public static new NetworkDnsmasqOptionsArgs Empty => new NetworkDnsmasqOptionsArgs();
    }
}
