// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Libvirt.Inputs
{

    public sealed class NetworkDnsmasqOptionsOptionGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("optionName")]
        public Input<string>? OptionName { get; set; }

        [Input("optionValue")]
        public Input<string>? OptionValue { get; set; }

        public NetworkDnsmasqOptionsOptionGetArgs()
        {
        }
        public static new NetworkDnsmasqOptionsOptionGetArgs Empty => new NetworkDnsmasqOptionsOptionGetArgs();
    }
}
