// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class CloudInitDisk extends pulumi.CustomResource {
    /**
     * Get an existing CloudInitDisk resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: CloudInitDiskState, opts?: pulumi.CustomResourceOptions): CloudInitDisk {
        return new CloudInitDisk(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'libvirt:index/cloudInitDisk:CloudInitDisk';

    /**
     * Returns true if the given object is an instance of CloudInitDisk.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is CloudInitDisk {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === CloudInitDisk.__pulumiType;
    }

    /**
     * cloud-init user data.
     */
    public readonly metaData!: pulumi.Output<string | undefined>;
    /**
     * A unique name for the resource, required by libvirt.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * cloud-init network-config data.
     */
    public readonly networkConfig!: pulumi.Output<string | undefined>;
    /**
     * The pool where the resource will be created.
     * If not given, the `default` pool will be used.
     * For user_data, networkConfig and metaData parameters have a look at upstream doc:
     * http://cloudinit.readthedocs.io/en/latest/topics/datasources/nocloud.html#datasource-nocloud
     */
    public readonly pool!: pulumi.Output<string | undefined>;
    /**
     * cloud-init user data.
     */
    public readonly userData!: pulumi.Output<string | undefined>;

    /**
     * Create a CloudInitDisk resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: CloudInitDiskArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: CloudInitDiskArgs | CloudInitDiskState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as CloudInitDiskState | undefined;
            resourceInputs["metaData"] = state ? state.metaData : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["networkConfig"] = state ? state.networkConfig : undefined;
            resourceInputs["pool"] = state ? state.pool : undefined;
            resourceInputs["userData"] = state ? state.userData : undefined;
        } else {
            const args = argsOrState as CloudInitDiskArgs | undefined;
            resourceInputs["metaData"] = args ? args.metaData : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["networkConfig"] = args ? args.networkConfig : undefined;
            resourceInputs["pool"] = args ? args.pool : undefined;
            resourceInputs["userData"] = args ? args.userData : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(CloudInitDisk.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering CloudInitDisk resources.
 */
export interface CloudInitDiskState {
    /**
     * cloud-init user data.
     */
    metaData?: pulumi.Input<string>;
    /**
     * A unique name for the resource, required by libvirt.
     */
    name?: pulumi.Input<string>;
    /**
     * cloud-init network-config data.
     */
    networkConfig?: pulumi.Input<string>;
    /**
     * The pool where the resource will be created.
     * If not given, the `default` pool will be used.
     * For user_data, networkConfig and metaData parameters have a look at upstream doc:
     * http://cloudinit.readthedocs.io/en/latest/topics/datasources/nocloud.html#datasource-nocloud
     */
    pool?: pulumi.Input<string>;
    /**
     * cloud-init user data.
     */
    userData?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a CloudInitDisk resource.
 */
export interface CloudInitDiskArgs {
    /**
     * cloud-init user data.
     */
    metaData?: pulumi.Input<string>;
    /**
     * A unique name for the resource, required by libvirt.
     */
    name?: pulumi.Input<string>;
    /**
     * cloud-init network-config data.
     */
    networkConfig?: pulumi.Input<string>;
    /**
     * The pool where the resource will be created.
     * If not given, the `default` pool will be used.
     * For user_data, networkConfig and metaData parameters have a look at upstream doc:
     * http://cloudinit.readthedocs.io/en/latest/topics/datasources/nocloud.html#datasource-nocloud
     */
    pool?: pulumi.Input<string>;
    /**
     * cloud-init user data.
     */
    userData?: pulumi.Input<string>;
}
